[project]
name = "template-aiogram3x-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Shkaf4i3",email = "fleximes@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "aiogram (>=3.22.0,<4.0.0)",
    "pydantic-settings (>=2.11.0,<3.0.0)",
    "fastapi[all] (>=0.121.1,<0.130.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "cryptography (>=46.0.4,<47.0.0)",
    "aiocryptopay (>=0.4.8,<0.5.0)",
]


[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
